name: canteen_kiosk_application
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  platform_device_id_v3: ^1.0.0
  google_fonts: ^6.2.1
  path_provider_windows: ^2.2.1
  hive: ^2.2.3
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  logger: ^2.1.0
  path_provider: ^2.1.2
  syncfusion_flutter_pdfviewer: ^22.2.5
  pdf: ^3.10.8
  printing: ^5.12.0
  carousel_slider: ^4.2.1
  number_to_words_english: ^2.0.2
  pinput: ^4.0.0
  msix: ^3.16.7
  qr_flutter: ^4.1.0
  connectivity_plus: ^6.0.1
  get_ip_address: ^0.0.6
  wifi_ip_details: ^1.0.0
  desktop_window: ^0.4.0
  toggle_switch: ^2.3.0
  flutter_oss_licenses: ^3.0.2
  intl: ^0.18.0
  cron: ^0.6.0
  syncfusion_flutter_charts: ^22.2.5
  flutter_typeahead: ^4.6.1
  pie_chart: ^5.4.0
  window_manager: ^0.3.8
  syncfusion_flutter_xlsio: ^22.2.10
  http: ^1.2.1
  file_picker: ^8.0.3
  mime: ^1.0.5
  http_parser: ^4.0.2
  ffi: ^2.1.2
  flutter_esc_pos_utils: ^1.0.1
  motion_toast: ^2.10.0
  win32: ^5.4.0
  typed_data: ^1.3.2
  sentry_flutter: ^8.2.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
    - assets/svg/
    - assets/printer_status.json
    - assets/OpenSans-Bold.ttf
    - assets/OpenSans-BoldItalic.ttf
    - assets/OpenSans-ExtraBold.ttf
    - assets/OpenSans-ExtraBoldItalic.ttf
    - assets/OpenSans-Italic.ttf
    - assets/OpenSans-Light.ttf
    - assets/OpenSans-LightItalic.ttf
    - assets/OpenSans-Medium.ttf
    - assets/OpenSans-MediumItalic.ttf

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  remove_alpha_ios: true
  adaptive_icon_background: "#621990"
  image_path: "assets/images/VMSLogo.jpeg"
  # min_sdk_android: 20 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"